name: jayk_delivery_app
description: A new Flutter project for Jayk Delivery App.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.24.2
  firebase_auth: ^4.15.2
  cloud_firestore: ^4.13.3
  firebase_messaging: ^14.7.14
  firebase_storage: ^11.7.0

  async: ^2.11.0

  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.65.0
  cupertino_icons: ^1.0.2

  intl: ^0.18.1
  uuid: ^4.2.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.4
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/fonts/Cairo-Regular.ttf
